[package]
name = "hello-dioxus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# if this fails to build, add the ayatana feature  
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-html = { git = "https://github.com/DioxusLabs/dioxus.git" }
tokio = { version = "1", features = ["full"] }


[build-dependencies]
glob = "0.3.0"
rsass = "0.26.0"